{
 "title": "Database Exporter",
 "tags": [
  "postgres",
  "metrics",
  "exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transaction per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_stat_database_numbackends", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "Active Queries Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration"
    }
   ]
  },
  {
   "title": "Database Size (MB)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes / 1024^3",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Disk Blocks Hit vs Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "pg_stat_database_blks_hit", "legendFormat": "Hits {{datname}}" },
    { "expr": "pg_stat_database_blks_read", "legendFormat": "Reads {{datname}}" }
   ]
  },
  {
   "title": "Replication Lag (seconds)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_replication_lag_seconds" }
   ]
  },
  {
   "title": "WAL Size (Bytes)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_wal_size_bytes" }
   ]
  },
  {
   "title": "Read I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read[5m]) * 8192",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions Committed vs Rolled Back",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "pg_stat_database_xact_commit", "legendFormat": "Committed {{datname}}" },
    { "expr": "pg_stat_database_xact_rollback", "legendFormat": "Rolled back {{datname}}" }
   ]
  },
  {
   "title": "Dead vs Live Tuples",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_dead_tup", "legendFormat": "Dead {{table}}" },
    { "expr": "pg_stat_user_tables_n_live_tup", "legendFormat": "Live {{table}}" }
   ]
  }
 ]
}